/// Flutter icons YvanIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  YvanIcons
///      fonts:
///       - asset: fonts/YvanIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class YvanIcons {
  YvanIcons._();

  static const _kFontFam = 'YvanIcons';
  static const _kFontPkg = null;

  static const IconData left_arrow = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData address = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_line = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file_2_line = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_bin_6_line = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout_box_line = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_list_add_fill = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_check = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bar_chart_line = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_right_s_line = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_drop_down_line = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData at_line = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down_s_line = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left_line = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_fill = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_drop_right_line = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_line = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clockwise = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData avatar = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete_1 = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bag = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit_2_line = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wholesaler = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_bag2 = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hourglass_1_ = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_cadenas = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData like = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData limited_time = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_utilisateur_masculin = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_line = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData building_2_line = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qr_code = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message_2_line = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repeat_2_line = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_dollar_circle_line = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send_plane_fill = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_off_line = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blue_girl_character = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_delete_line = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData archive_line = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attachment_line = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_line = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData community_line = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_settings_fill = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_bag = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData offer = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_2_fill = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData global_line = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_1_line = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_to_favorite = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_line = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alert_line = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close_fill = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emotion_sad_line = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_line = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData blue_man_character = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_line = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData followers = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_2_line = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coupon = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stopwatch = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData love_letter = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wishlist = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_6_line = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brand = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_bag_3_line = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_pin_2_line = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_2_line = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkbox_circle_line = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_password_line = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_circle_line = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_arrow_1 = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification_4_line = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh_line = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cosmetics = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData placeholder = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData integration = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gender = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet_filled_money_tool = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_cart_line = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loupe = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
